server:
  port: 8010

#application.name: 当前服务注册在Eureka Server上的名称
spring:
  application:
    name: provider

#server-url.defaultZone: 注册中心的访问地址
#instance.prefer-ip-address: 是否将当前服务的IP注册到Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true