#当前Eureka Server服务端口
server:
  port: 8761

#register-with-eureka：是否将当前的Eureka Server服务当做客户端注册
#fetch-registry：是否获取其他Eureka Server服务的数据
#service-url.defaultZone：注册中心的访问地址
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/